services:
  database:
    container_name: sportsradar_database
    image: postgres:14.10-alpine3.19
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGPORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
  smtp:
    container_name: sportsradar_smtp_server
    image: marcopas/docker-mailslurper
    restart: always
    ports:
      - 8081:8080
      - 25:2500
      - 8888:8888


volumes:
  pgdata: